# Generated by Django 3.0.4 on 2020-03-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
